<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Data\" />
    <Folder Include="Reports\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".claude\dbmodel.md" />
    <None Include=".claude\flow.md" />
    <None Include=".claude\stack.md" />
  </ItemGroup>

  <ItemGroup>
    <None Include="config.ini" CopyToOutputDirectory="PreserveNewest" />
    <None Include="config.exemplo.ini" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FirebirdSql.EntityFrameworkCore.Firebird" Version="13.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Ini" Version="10.0.12" />
    <PackageReference Include="QuestPDF" Version="2026.9.1" />
  </ItemGroup>

</Project>
